### ISSUE TITLE
Update CADD indel to v1.7

### ISSUE THREAD

**Issue by Jakob37** [Clinical-Genomics-Lund/nextflow_wgs#163]

**Comment by Jakob37** [comment]
After some fiddling some error messages were resolved. But still others remain:

* `-q` flag was needed to not crash
* Binding in the `conda` folder from `tmp` was needed as it tried doing changes there

```
singularity exec -B /fs1 -B /tmp/cadd17:/usr/local/share/cadd-scripts-1.7-0/envs/conda /fs1/resources/containers/cadd_v1.7.sif cadd.sh -c 1 -g GRCh38 -o test.gz -q in.vcf
```

Here it still crashes due to not finding conda:

```
CADD-v1.7 (c) University of Washington, Hudson-Alpha Institute for Biotechnology and Berlin Institute of Health at Charité - Universitätsmedizin Berlin 2013-2023. All rights reserved.
Running snakemake pipeline:
snakemake /tmp/tmp.2jyG50/24MD01205-tiddit-wgs_single-test.only_indels.tsv.gz --use-conda --conda-prefix /usr/local/share/cadd-scripts-1.7-0/envs/conda --cores 1
--configfile /usr/local/share/cadd-scripts-1.7-0/config/config_GRCh38_v1.7_noanno.yml --snakefile /usr/local/share/cadd-scripts-1.7-0/Snakefile
Building DAG of jobs...
/usr/bin/bash: line 1: conda: command not found
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/snakemake/cli.py", line 1970, in args_to_api
    dag_api.execute_workflow(
  File "/usr/local/lib/python3.12/site-packages/snakemake/api.py", line 579, in execute_workflow
    workflow.execute(
  File "/usr/local/lib/python3.12/site-packages/snakemake/workflow.py", line 1103, in execute
    self.dag.create_conda_envs()
  File "/usr/local/lib/python3.12/site-packages/snakemake/dag.py", line 414, in create_conda_envs
    env.create(self.workflow.dryrun)
  File "/usr/local/lib/python3.12/site-packages/snakemake/deployment/conda.py", line 393, in create
    pin_file = self.pin_file
               ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/snakemake_interface_common/utils.py", line 30, in __get__
    value = self.method(instance)
            ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/snakemake/deployment/conda.py", line 103, in pin_file
    f".{self.conda.platform}.pin.txt"
        ^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/snakemake_interface_common/utils.py", line 30, in __get__
    value = self.method(instance)
            ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/snakemake/deployment/conda.py", line 96, in conda
    return Conda(
           ^^^^^^
  File "/usr/local/lib/python3.12/site-packages/snakemake/deployment/conda.py", line 653, in __init__
    shell.check_output(self._get_cmd("conda info --json"), text=True)
  File "/usr/local/lib/python3.12/site-packages/snakemake/shell.py", line 61, in check_output
    return sp.check_output(cmd, shell=True, executable=executable, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'conda info --json' returned non-zero exit status 127.
```
